root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/docs/fontawesome-bundle
        permanent: false

locale:
    pattern: /en
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/docs/fontawesome-bundle
        permanent: false

docs:
    pattern: /en/docs
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/docs/fontawesome-bundle
        permanent: false

fontawesome:
    resource: "@FontAwesomeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/docs/fontawesome-bundle
    requirements:
        _locale: en|fr
